const ducks = [
    {
        color: 'blue',
        isRubber: true,
        gender: 'female',
        isMigrator: true,
        socialStatus: 'ready to mingle',
        diet: 'vegan',
        age: 47, 
        featherNum: 0,
        name: 'Regina',
        imgUrl: 'https://toppng.com/uploads/preview/blue-rubber-duck-11563236196ld4tpdeogb.png',
    },
    {
        color: 'white',
        isRubber: false,
        gender: 'female',
        isMigrator: true,
        socialStatus: 'ready to mingle',
        diet: 'vegan',
        age: 47, 
        featherNum: 0,
        name: 'Lois',
        imgUrl: 'https://p7.hiclipart.com/preview/107/467/622/domestic-goose-duck-feather-big-white-goose-farm.jpg'
    },
    {
        color: 'blue',
        isRubber: false,
        gender: 'female',
        isMigrator: true,
        socialStatus: 'ready to mingle',
        diet: 'vegan',
        age: 47, 
        featherNum: 0,
        name: 'BluBri',
        imgUrl: 'https://images.fineartamerica.com/images-medium-large/blue-winged-teal-anas-discors-female-scott-leslie.jpg',
    },
    {
        color: 'yellow',
        isRubber: false,
        gender: 'male',
        isMigrator: true,
        socialStatus: 'ready to mingle',
        diet: 'vegan',
        age: 47, 
        featherNum: 0,
        name: 'Sunshine',
        imgUrl: 'https://i.pinimg.com/originals/9d/bd/20/9dbd20a1dd70777335479fa4118ead27.jpg',
    },
    {
        color: 'blue',
        isRubber: true,
        gender: 'male',
        isMigrator: true,
        socialStatus: 'ready to mingle',
        diet: 'vegan',
        age: 47, 
        featherNum: 0,
        name: 'Bob',
        imgUrl: 'https://shop.r10s.jp/stab-blue/cabinet/05851142/imgrc0092164782.jpg',
    },
    {
        color: 'white',
        isRubber: false,
        gender: 'male',
        isMigrator: true,
        socialStatus: 'ready to mingle',
        diet: 'vegan',
        age: 47, 
        featherNum: 0,
        name: 'Ted',
        imgUrl: 'https://us.123rf.com/450wm/gumpapa/gumpapa1510/gumpapa151000033/47332942-white-duck-stand-next-to-a-pond-or-lake-with-bokeh-background.jpg?ver=6',
    },
    {
        color: 'blue',
        isRubber: true,
        gender: 'male',
        isMigrator: true,
        socialStatus: 'ready to mingle',
        diet: 'vegan',
        age: 47, 
        featherNum: 0,
        name: 'Doc',
        imgUrl: 'https://cdn11.bigcommerce.com/s-nf2x4/images/stencil/1280x1280/products/1012/10059/Surgeon-Blue-Rubber-Duck-Adline-3__58755.1568649695.jpg?c=2&imbypass=on',
    },
    {
        color: 'yellow',
        isRubber: false,
        gender: 'male',
        isMigrator: true,
        socialStatus: 'ready to mingle',
        diet: 'vegan',
        age: 47, 
        featherNum: 0,
        name: 'Rick',
        imgUrl: 'https://i.pinimg.com/originals/40/94/f3/4094f3f5cefefc041a47b766a97f3fff.jpg',
    }
];

console.log(ducks)

